name: Deploy Backend

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install SSH key
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa $VPS_HOSTNAME >> ~/.ssh/known_hosts

    - name: Deploy backend
      run: |
        ssh natsu@$VPS_HOSTNAME 'cd project/Backend/ && git pull && npm install && pm2 restart www'
